In [0]:
#importing pandas library
import pandas as pd
#importing numpy library
import numpy as np

In [74]:
#creating my dataset
url='Autolib_dataset (2) (1).csv'
df=pd.read_csv(url)
df

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

In [75]:
#Action: Checking the dataframe information
df.dtypes

Address                object
Cars                    int64
Bluecar counter         int64
Utilib counter          int64
Utilib 1.4 counter      int64
Charge Slots            int64
Charging Status        object
City                   object
Displayed comment      object
ID                     object
Kind                   object
Geo point              object
Postal code             int64
Public name            object
Rental status          object
Scheduled at           object
Slots                   int64
Station type           object
Status                 object
Subscription status    object
year                    int64
month                   int64
day                     int64
hour                    int64
minute                  int64
dtype: object

In [76]:
#Action: Checking to see whether columns have null values
df.isnull().sum()

Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

In [77]:
#Action: Dropping the columns that have null values close to the number of rows of the dataset
df.drop(["Scheduled at", "Displayed comment"], axis=1, inplace=True)
df

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 23 columns]

In [78]:
#Action: Cross-checking to see that all null values are removed
df.isnull().sum()

Address                0
Cars                   0
Bluecar counter        0
Utilib counter         0
Utilib 1.4 counter     0
Charge Slots           0
Charging Status        0
City                   0
ID                     0
Kind                   0
Geo point              0
Postal code            0
Public name            0
Rental status          0
Slots                  0
Station type           0
Status                 0
Subscription status    0
year                   0
month                  0
day                    0
hour                   0
minute                 0
dtype: int64

In [79]:
#Action: Renaming specific columns
df.rename(columns={"year": "Year", "month" : "Month", "day": "Day", "hour" : "Hour", "minute" : "Minute", "Charge Slots": "Charge slots", "Charging Status": "Charging status" }, inplace=True)
df

                                 Address  Cars  ...  Hour  Minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 23 columns]

In [80]:
#Action:checking for duplicates
#Explanation: No duplicates
duplicated=df.drop_duplicates()
duplicated

                                 Address  Cars  ...  Hour  Minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 23 columns]

In [81]:
#the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

new_df=df[(df['Rental status']=="operational") & (df['Bluecar counter']>0) & (df['Month']==4) & (df['City']=="Paris") & (df['Kind']=="STATION")]
new_df
print(new_df['Hour'].mode(),"\n") #most popular hour of the day for picking up
print(new_df['Hour'].value_counts().sort_values(ascending=False)) #pick the firt one

0    21
dtype: int64

21    85
12    83
15    76
10    75
16    73
13    73
8     73
17    72
6     72
9     69
18    69
5     68
19    68
7     65
2     65
22    63
0     62
4     62
3     62
23    61
11    61
20    59
14    57
1     56
Name: Hour, dtype: int64

In [82]:
#21 is still the most popular hour for renting any car
new_df=df[(df['Rental status']=="operational") & (df['Month']==4) & (df['City']=="Paris") & (df['Kind']=="STATION")]
new_df['Hour'].mode()

0    21
dtype: int64

In [83]:
#counting the instances in which there were no cars available for renting at the most popular hour
df1=df[(df['Bluecar counter']==0) & (df['Utilib counter']==0) & (df['Utilib 1.4 counter']==0) & (df['Hour']==21) & (df['Rental status']== "operational") & (df['Kind']== "STATION") & (df['City']== "Paris")]
df1['Hour'].value_counts()

21    30
Name: Hour, dtype: int64

In [87]:
#the most popular station at the popular picking hour
new_df2=df[(df['Hour']==21) & (df['Rental status']== "operational") & (df['Kind']=="STATION")]
new_df2['Public name'].value_counts().nlargest(1)

Paris/Tronchet/19    4
Name: Public name, dtype: int64

In [94]:
#checking how many people had an operational subscription status
df[df['Subscription status']=="operational"].count()

Address                264
Cars                   264
Bluecar counter        264
Utilib counter         264
Utilib 1.4 counter     264
Charge slots           264
Charging status        264
City                   264
ID                     264
Kind                   264
Geo point              264
Postal code            264
Public name            264
Rental status          264
Slots                  264
Station type           264
Status                 264
Subscription status    264
Year                   264
Month                  264
Day                    264
Hour                   264
Minute                 264
dtype: int64